name: 'API Client Jobs'

on:
  workflow_dispatch:

  workflow_run:
    types:
      - completed
    workflows:
      - 'Server Jobs'

jobs:
  update_package_version:
    name: Update package version
    runs-on: ubuntu-latest

    env:
      SERVER_REPO: ${{ github.repository_owner }}/Server

    steps:
      - name: Checkout server
        uses: actions/checkout@v4
        with:
          repository: ${{ env.SERVER_REPO }}
          ref: "main"
          token: ${{ secrets.ACCESS_TOKEN }}
          path: ./server

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: corretto

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2.0.0

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3.0.0

      - name: Giving permission to Gradle
        run: chmod +x ./gradlew
        working-directory: ./server

      - name: Get server version
        run: |
          SERVER_VERSION=$(./gradlew properties -q | awk '/^version:/ {print $2}')
          echo "SERVER_VERSION=$SERVER_VERSION" >> $GITHUB_ENV
        working-directory: ./server

      - name: Checkout API
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: Set package version
        run: |
          node version.js ${{ env.SERVER_VERSION }}

      - name: Commit updated package version
        run: |
          git config --global user.name 'Github Action'
          git config --global user.email 'bot@noreply.github.com'
          git add package.json
          git remote set-url origin https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "CI: Auto updated package version" && git push || echo "No changes to commit"

  build:
    name: 'Build API client and Publishing it'
    runs-on: ubuntu-latest

    needs:
      - update_package_version

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: Resolve dependencies
        run: npm ci

      - name: Build API client
        run: 'npm run build'

      - name: Publishing API client to Github Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

