name: 'Server jobs'

on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'Event Handler: on Server Repository Updated'

jobs:
  update_submodules:
    name: Update submodules
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: true

      - name: Update submodules
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

      - name: Commit update
        run: |
          git config --global user.name 'Github Action'
          git config --global user.email 'bot@noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "CI: Auto updated submodule references" && git push || echo "No changes to commit"

  build_api:
    name: Build Server API Specification
    runs-on: ubuntu-latest

    needs:
      - update_submodule

    steps:
      - name: Checkout
        uses: action/checkout@v4
        with:
          repository: "${{ github.repository_owner }}/Server"
          ref: "main"
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: termurin

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2.0.0

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3.0.0

      - name: Build server by Gradle
        run: ./gradlew build -x test

      - name: Get Server Version
        run: |
          ./gradlew properties -q | awk '/^version:/ {print $2}' >> $SERVER_VERSION
          echo "SERVER_VERSION=$SERVER_VERSION" >> $GITHUB_ENV

      - name: Echo Server Version
        run: echo ${{ env.SERVER_VERSION }}
