name: 'Update submodules'

on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'Event Handler: on Server Repository Updated'

jobs:
  update_submodules:
    name: Update submodules
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: true

      - name: Update submodules
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

      - name: Commit update
        run: |
          git config --global user.name 'Github Action'
          git config --global user.email 'bot@noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "CI: Auto updated submodule references" && git push || echo "No changes to commit"
